### ISSUE TITLE
I can't open the embeddings

### ISSUE THREAD

**Issue by andreamad8** [tbmihailov/semeval2016-task3-cqa#1]
Hi, 
I'm trying to use the embeddings that you have linked. I use the following code (as in the example):

```python
word2vec_model_file='../embeddings/qatarliving_qc_size100_win10_mincnt5_rpl_skip1_phrFalse_2016_02_23.word2vec.bin'
model = Word2Vec.load_word2vec_format(word2vec_model_file, binary=False ,encoding="ISO-8859-1")
print(model['qatar'])
```
but I have got the following error:
```python
Traceback (most recent call last):
  File "ann_model.py", line 59, in <module>
    model = Word2Vec.load_word2vec_format(word2vec_model_file, binary=False ,encoding="ISO-8859-1")
  File "/home/andrea/anaconda3/lib/python3.5/site-packages/gensim/models/word2vec.py", line 1173, in load_word2vec_format
    vocab_size, vector_size = map(int, header.split())  # throws for invalid file format
ValueError: invalid literal for int() with base 10: '\x80\x02cgensim.models.word2vec'
```

Have you ever had this problem? I have tried to google it, with no success. 
May I know how have you generated the embeddings? 

Thanks in advance

**Comment by tbmihailov** [comment]
Hi,

Sorry for the late reply. I see that you use ISO-8859-1 encoding. You should use utf-8.

**Comment by tbmihailov** [comment]
Actually the code was wrong. It is now fixed:

```python
word2vec_model_file='qatarliving_qc_size200_win5_mincnt1_rpl_skip3_phrFalse_2016_02_25.word2vec.bin' # put here the .bin file from the downloaded zip file

#load the model
model = Word2Vec.load(word2vec_model_file)

#evaluate
print model.most_similar(positive=['woman', 'king'], negative=['man'], topn=1)

#get embedding for word
print model['qatar']

```

Let me know if it works for you.

**Comment by andreamad8** [comment]
Hi, 

now it seams working, thanks a lot for your support. 

Best
